version: '3.5'
services:
  my-go-hello-world:
    container_name: go-rest-api
    build: .
    ports: 
      - 8000:8000
    command: go run main.go
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
